{% set name = "go-sqlcmd" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/microsoft/go-sqlcmd/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c134f62de37e5b0e32d27219b4d5dd96ddce0b6aecafa22c1ae869128fa7b514

build:
  number: 0
  script: |
    set -eoux pipefail
    go install ./cmd/sqlcmd
    # FIXME: Remove ignore once depending on 0.8.3 or later
    # https://github.com/Azure/azure-sdk-for-go/issues/16203#issuecomment-971695479
    go-licenses save --ignore="github.com/Azure/azure-sdk-for-go" --save_path="./thirdparty" ./cmd/sqlcmd

requirements:
  build:
    - {{ compiler('go') }}
    - go-licenses >=1.2.1

test:
  commands:
    - sqlcmd --help

about:
  home: https://github.com/microsoft/go-sqlcmd
  summary: Native go implementation of sqlcmd
  license: MIT
  license_file:
    - LICENSE
    - thirdparty/

extra:
  recipe-maintainers:
    - dhirschfeld
