{% set name = "go-sqlcmd" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/microsoft/go-sqlcmd/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f200155b4233fc7d8f632800705bae19eaa338a9c82c3f9d9106cbf3dcb78a8e

build:
  number: 0
  script: |
    set -eoux pipefail
    go build -ldflags="-X main.version={{ version }}" -o $PREFIX/bin/sqlcmd ./cmd/modern  # [not win]
    go build -ldflags="-X main.version={{ version }}" -o %PREFIX%/bin/sqlcmd ./cmd/modern  # [win]
    go-licenses save --save_path="./thirdparty" ./cmd/modern

requirements:
  build:
    - {{ compiler('go') }}
    - go-licenses >=1.2.1

test:
  commands:
    - sqlcmd --help  # [not win]
    - sqlcmd -?  # [win]

about:
  home: https://github.com/microsoft/go-sqlcmd
  summary: Native go implementation of sqlcmd
  license: MIT
  license_file:
    - LICENSE
    - thirdparty/

extra:
  recipe-maintainers:
    - dhirschfeld
