{% set name = "go-sqlcmd" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/microsoft/go-sqlcmd/archive/refs/tags/v{{ version }}.tar.gz
  sha256: de9f0331d680914c13db791169da46c66f68affc006fbab2324ff77f9b4903be

build:
  number: 0
  script: |
    set -eoux pipefail
    go build -ldflags="-X main.version={{ version }}" -o $PREFIX/bin/sqlcmd ./cmd/modern  # [not win]
    go build -ldflags="-X main.version={{ version }}" -o %PREFIX%/bin/sqlcmd ./cmd/modern  # [win]
    go-licenses save --save_path="./thirdparty" ./cmd/modern

requirements:
  build:
    - {{ compiler('go') }}
    - go-licenses >=1.2.1

test:
  commands:
    - sqlcmd --help  # [not win]
    - sqlcmd -?  # [win]

about:
  home: https://github.com/microsoft/go-sqlcmd
  summary: Native go implementation of sqlcmd
  license: MIT
  license_file:
    - LICENSE
    - thirdparty/

extra:
  recipe-maintainers:
    - dhirschfeld
